version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot_vinos_development
    ports:
      - "5432:5432"

  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - ".:/rails"
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      RAILS_ENV: development
      RAILS_MASTER_KEY: ad8037180ce6de41c0aa388ce923a136
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: chatbot_vinos_development
    depends_on:
      - db
